import type { Metadata } from "next";
import localFont from "next/font/local";
// import Script from "next/script";

const myFont = localFont({
  src: "../../public/fonts/ScholarlyAmbition-Regular.ttf",
});

export const metadata: Metadata = {
  title: "birthday day",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
