import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
// import Script from "next/script";

const scholarlyAmbition = localFont({
  src: "../../public/fonts/ScholarlyAmbition-Regular.woff",
  display: "swap",
});

export const metadata: Metadata = {
  title: "birthday day",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa-IR">
      <body className={`${scholarlyAmbition.className} bg-black`}>
        {children}
      </body>
    </html>
  );
}
